"""
Chat orchestration: input guardrail -> RAG pipeline -> output guardrail.

patient_id is resolved from the session, never from the request body.
See app/rag/pipeline.py for the retrieval/generation flow itself.
"""

from __future__ import annotations

import uuid

from app.guardrails.input import InputGuardrail, InputGuardrailBlocked
from app.guardrails.output import OutputGuardrail
from app.guardrails.trajectory import TrajectoryGuardrail
from app.rag.pipeline import RagPipeline
from app.rag.types import ScoredChunk
from app.schemas.chat import ChatResponse, SourceRef
from app.services.session_service import SessionService


class ChatService:
    def __init__(self, session_service: SessionService, rag_pipeline: RagPipeline, input_guardrail: InputGuardrail,
                 output_guardrail: OutputGuardrail, trajectory_guardrail: TrajectoryGuardrail | None = None) -> None:

        self._session_service = session_service
        self._rag_pipeline = rag_pipeline
        self._input_guardrail = input_guardrail
        self._output_guardrail = output_guardrail
        self._trajectory_guardrail = trajectory_guardrail

    def handle_chat(self, session_id: str, message: str) -> ChatResponse:
        session = self._session_service.get_session(session_id)
        patient_id = session.patient_id
        history = list(session.messages)

        # Input guardrails
        try:
            # Analyze new user message
            clean_message = self._input_guardrail.check(message, session_id)

            # Analyze conversation history (if enabled)
            if self._trajectory_guardrail is not None:
                self._trajectory_guardrail.check(clean_message, session_id, history)
        
        # Return an answer generated by an input guardrail (e.g a fallback answer) instead of passing the message on to the RAG
        except InputGuardrailBlocked as blocked:
            self._session_service.append_message(session_id, "user", message)
            self._session_service.append_message(session_id, "assistant", blocked.response)
            return ChatResponse(message_id=str(uuid.uuid4()), response=blocked.response, sources=[])

        # Prompt LLM
        self._session_service.append_message(session_id, "user", clean_message)
        result = self._rag_pipeline.run(question=clean_message, patient_id=patient_id, history=history)

        # Output guardrails
        final_answer = self._output_guardrail.check(result.answer)

        self._session_service.append_message(session_id, "assistant", final_answer)

        # For Debugging: Determine which sources/records have been retrieved by the RAG pipeline
        sources = [SourceRef(source_record_id=sc.chunk.source_record_id, section=sc.chunk.section) 
                   for sc in _dedupe_by_source(result.chunks_used)]
        
        return ChatResponse(message_id=str(uuid.uuid4()), response=final_answer, sources=sources)


# Create list of chunks that come from different sources
def _dedupe_by_source(chunks: list[ScoredChunk]) -> list[ScoredChunk]:

    seen: set[tuple[str, str]] = set()
    deduped: list[ScoredChunk] = []

    for sc in chunks:
        key = (sc.chunk.source_record_id, sc.chunk.section)
        if key not in seen:
            seen.add(key)
            deduped.append(sc)

    return deduped
